---
- name: Ensure git is installed (RedHat).
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: "{{ git_enablerepo }}"
  with_items: "{{ git_packages }}"
  when: ansible_os_family == 'RedHat'

- name: Update apt cache (Debian).
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Ensure git is installed (Debian).
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ git_packages }}"
  when: ansible_os_family == 'Debian'

